apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: group-labeling-job
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: group-labeling-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: group-labeling-job:latest
    source:
      type: Git
      git: 
        uri: "https://github.com/cnuland/GroupLabelingJob"
        ref: "master"
      contextDir: "job/"
    strategy:
      dockerStrategy:
        buildArgs:
        - name: OCP_VERSION
          value: "4.3"
        from:
          kind: ImageStreamTag
          name: ubi8:latest
      type: Docker
    postCommit: {}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange