apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: group-label-job
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cron-group-label-job"
        spec:
          containers:
          - name: group-label-job
            image: group-labeling-job:latest
            command: ["python3", "group-label.py"]
          restartPolicy: OnFailure
          serviceAccount: group-label-robot
          serviceAccountName: group-label-robot